/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['logger.js']) {
  _$jscoverage['logger.js'] = [];
  _$jscoverage['logger.js'][1] = 0;
  _$jscoverage['logger.js'][2] = 0;
  _$jscoverage['logger.js'][3] = 0;
}
_$jscoverage['logger.js'][1]++;
module.exports = (function () {
  _$jscoverage['logger.js'][2]++;
  console.log("Testing expresso");
  _$jscoverage['logger.js'][3]++;
  return "test";
});
_$jscoverage['logger.js'].source = ["module.exports = function(){","  console.log('Testing expresso');","  return 'test';","}"];
